#! /usr/bin/env bash

# Enable advanced globbing
shopt -s globstar

preferences () {
    LANG='C.UTF-8' TIME_STYLE='long-iso' $1
}

_lhal () {
    ls -hal
}

lhal () {
    # List files with human readable sizes, even the hidden ones, the long way.
    preferences _lhal
}

_lha1 () {
    ls -ha1
}

lha1 () {
    # List files with human readable sizes, even the hidden ones,
    # the short way.
    preferences _lha1
}

randstring () {
    n="${1:-16}"
    nBytes="$(($n * 2))"
    head -"$nBytes" /dev/urandom | LC_ALL=c tr -dc 'a-zA-Z0-9\-\+\!' | fold -w "$n" | head -n 1
}

findex () {
    # Find paths in directory $1 matching the regex in $2
    # The regex should be enclosed in quotes to avoid globbing
    find ${1:?'Must set path'} \
        -regex ${2:?'Must set regex'} \
        -regextype posix-extended
}

cdp () {
    pushd $*
    cd $*
}

cdl () {
    cd $*
    find . -mindepth 1 -maxdepth 1 -type d -printf "%f/\n"
}

alias xcc='xclip -selection c'

export PS1EscStart='\['
export PS1EscEnd='\]'

function setColor () {
	echo "$(tput setaf $1)"
}

function unsetStyling () {
	echo "$(tput sgr0)"
}

function color () {
    case "${1:-'white'}" in
        'red')
            setColor 1
            ;;
        'green')
            setColor 2
            ;;
        'yellow')
            setColor 3
            ;;
        'powderBlue')
            setColor 153
            ;;
        'blue')
            setColor 4
            ;;
        'magenta')
            setColor 5
            ;;
        'cyan')
            setColor 6
            ;;
        'white')
            setColor 7
            ;;
        'unset')
            unsetStyling
            ;;
        *)
            setColor 7
            ;;
    esac
}

function setStyle () {
    echo "$(tput $1)"
}

function style () {
    case "${1:-'normal'}" in
        'bold')
            setStyle bold
            ;;
        'underline')
            setStyle smul
            ;;
        'blink')
            setStyle blink
            ;;
        'reverse')
            setStyle smso
            ;;
        'normal')
            unsetStyling
            ;;
        'unset')
            unsetStyling
            ;;
        *)
            unsetStyling
            ;;
    esac
}

function colorThis () {
    echo "$(color ${1})${2}$(color unset)"
}

function styleThis () {
    echo "$(style ${1})${2}$(style unset)"
}

function styleColorThis () {
    echo "$(style ${1})$(color ${2})${3}$(color unset)$(style unset)"
}

alias ct=colorThis
alias sct=styleColorThis

git config --global alias.logpo 'log --pretty=oneline'
git config --global alias.logshort 'log --pretty="format:%C(auto,yellow)%h%C(auto,magenta)% G? %C(auto,blue)%>(12,trunc)%ad %C(auto,green)%<(7,trunc)%aN%C(auto,reset)%s%C(auto,red)% gD% D" --date=short'
git config --global alias.s 'stage'
git config --global alias.cm 'commit -m'
git config --global alias.csm 'commit -S -m'
git config --global alias.sCm '!f() { git stage "${GIT_PREFIX}${1:?}" && git commit -m "${2:?}"; }; f'
git config --global alias.sCsm '!f() { git stage "${GIT_PREFIX}${1:?}" && git commit -S -m "${2:?}"; }; f'
