#! /usr/bin/env bash

preferences () {
    LANG='C.UTF-8' TIME_STYLE='long-iso' $1
}

_lhal () {
    ls -hal
}

lhal () {
    # List files with human readable sizes, even the hidden ones, the long way.
    preferences _lhal
}

_lha1 () {
    ls -ha1
}

lha1 () {
    # List files with human readable sizes, even the hidden ones,
    # the short way.
    preferences _lha1
}
